README.md, rs/README.md, ts/README.md, ts/src/main/main.ts
It was about time to clean up the README :slightly_smiling_face:
=> [all] Update `README.md`

rs/src/parsers/button.rs, ts/src/lib/parsers/button.ts
See https://github.com/open-flash/swf-parser/pull/5#issuecomment-478006639
=> [rs] Accept key code 8 in button cond

rs/Cargo.lock, rs/Cargo.toml, ts/package.json
- **[Breaking change]** Update to `swf-tree@0.4.x`
- **[Feature]** Implement parsers for the following tags: `DoAbc`, `ScriptLimits`, `SoundBlock`, `SoundHead`, `SoundHead2`, `StartSound`, `StartSound2`, `SymbolClass`
- **[Fix]** Drop JpegTables signature check
- **[Fix]** Update dependencies
- **[Fix]** [rs] Synchronize implementation with Typescript
- **[Fix]** [rs] Use pure-Rust libraries for decompression. Thanks @eddyb
- **[Fix]** [rs] Accept key code 8 in button cond
- **[Fix]** [rs] Keep opaque length in `x-ajpeg` image data
- **[Fix]** [rs] Update to Rust 2018
- **[Internal]** Add Travis CI integration
- **[Internal]** Update README.md
=> [all] Release v0.3.0

rs/Cargo.lock, rs/Cargo.toml, ts/package.json
- **[Fix]** Fix support for `DefineButton2` with multiple `ButtonCondAction`.
- **[Fix]** Update dependencies.
- **[Internal]** Update test samples.
=> [all] Release v0.3.1

rs/Cargo.lock, rs/Cargo.toml, ts/package.json
- **[Fix]** Fix `ButtonCond` parser
=> [all] Release v0.3.2

README.md, rs/README.md, ts/README.md
Shorten the `maxAge` of the badges from 30 days to 1 day.
=> [all] Shorten badge maxAge in `README.md`

rs/Cargo.lock, rs/Cargo.toml, rs/src/parsers/morph_shape.rs, rs/src/parsers/shape.rs, ts/package.json, ts/src/lib/parsers/morph-shape.ts, ts/src/lib/parsers/shape.ts, ts/yarn.lock
This commit updates the parser to use the new unified representation for edges. The presence of a control point determines the type of the edge. In the case of curved edges, `delta` is the difference between the start and end of the edges, it corresponds to the sum of the old `control_delta` and `anchor_delta`.
=> [all] Update to `swf-tree@0.5.0`

rs/Cargo.lock, rs/Cargo.toml, ts/package.json
- **[Breaking change]** Update to `swf-tree@0.5.0`.
=> [all] Release v0.4.0

rs/Cargo.lock, rs/Cargo.toml, rs/src/parsers/tags.rs, ts/package.json, ts/src/lib/parsers/display.ts, ts/src/lib/parsers/tags.ts, ts/yarn.lock
Despite being a major update, most of the changes are internal and should not affect consumers.
=> [all] Update to `swf-tree@0.6.0`

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, ts/package.json, ts/src/test/movies.spec.ts
- **[Fix]** Fix `TextRecord` flags parsing.
=> [all] Release v0.5.1

CHANGELOG.md, ts/README.md, ts/gulpfile.ts, ts/package.json, ts/src/lib/parsers/tags.ts, ts/yarn.lock
This commit updates to `turbo-gulp@0.20.0`. The main difference is that some tasks were renamed to be simpler.
=> [ts] Update build tools

CHANGELOG.md, rs/src/parsers/tags.rs, ts/src/lib/parsers/tags.ts, ts/src/test/tags.spec.ts
Closes open-flash/swf-parser#38
=> [all] Implement parser for `DefineFont2`

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, ts/package.json
- **[Feature]** Implement parser for `DefineFont2` ([#38](https://github.com/open-flash/swf-parser/issues/38)).
- **[Internal]** Update `Contributing` sections in `README.md`.
- **[Internal]** Update build tools.
=> [all] Release v0.5.4

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, rs/src/lib.rs, rs/src/parsers/display.rs, rs/src/parsers/tags.rs, ts/package.json, ts/src/lib/parsers/display.ts, ts/src/lib/parsers/tags.ts, ts/src/test/tags.spec.ts, ts/yarn.lock
This commit also includes fixes for non-extended clip actions.
- Closes open-flash/swf-parser#32
- Closes open-flash/swf-parser#33
=> [all] Implement parser for `DefineFont` and `DefineFontInfo`

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, ts/package.json
- **[Feature]** Implement parser for `Protect` ([#36](https://github.com/open-flash/swf-parser/issues/36)).
- **[Feature]** Implement parser for `DefineFont` ([#32](https://github.com/open-flash/swf-parser/issues/32)).
- **[Feature]** Implement parser for `DefineFontInfo` ([#33](https://github.com/open-flash/swf-parser/issues/33)).
- **[Fix]** Fix support for non-extended (SWF version < 6) clip actions in `PlaceObject2`.
- **[Internal]** Migrate CI to `travis-ci.com`.
- **[Internal]** Add `rustfmt` support (thanks [@pheki](https://github.com/pheki)) ([#25](https://github.com/open-flash/swf-parser/issues/25))
=> [all] Release v0.7.1

CHANGELOG.md, rs/rustfmt.toml, rs/src/parsers/tags.rs, ts/src/lib/parsers/tags.ts
Closes #31. I've tested it with open-flash-db/tags#1.
=> [all] Implement parser for DefineButton

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, rs/src/parsers/button.rs, rs/src/parsers/tags.rs, ts/package.json, ts/src/lib/parsers/button.ts, ts/src/lib/parsers/sound.ts, ts/src/lib/parsers/tags.ts
Also fixes a bug in the TS parser for `SoundInfo`.
Closes https://github.com/open-flash/swf-parser/issues/34
=> [all] Implement parser for `DefineButtonSound`

CHANGELOG.md, rs/Cargo.lock, rs/src/parsers/tags.rs, rs/src/parsers/text.rs
Closes https://github.com/open-flash/swf-parser/issues/37
=> [all] Implement parser for `DefineText2`

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, rs/src/parsers/tags.rs, ts/package.json, ts/src/lib/parsers/tags.ts, ts/yarn.lock
Closes open-flash/swf-parser#35
=> [all] Implement parser for `DefineButtonColorTransform`

CHANGELOG.md, rs/src/parsers/tags.rs, ts/src/lib/parsers/tags.ts
Closes open-flash/swf-parser#92
=> [all] Implement parser for `EnablePostscript`

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, rs/src/parsers/tags.rs, ts/.editorconfig, ts/package.json, ts/src/lib/parsers/tags.ts, ts/yarn.lock
Closes open-flash/swf-parser#41
=> [all] Implement parser for `VideoFrame`

CHANGELOG.md, rs/src/parsers/tags.rs, ts/src/lib/parsers/tags.ts
Closes open-flash/swf-parser#44
=> [all] Implement parser for `SetTabIndex`

rs/src/parsers/tags.rs, ts/src/lib/parsers/tags.ts
Closes open-flash/swf-parser#45
=> [all] Implement parser for `DefineScalingGrid`

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, rs/src/parsers/tags.rs, rs/src/parsers/text.rs, ts/package.json, ts/src/lib/parsers/tags.ts, ts/src/lib/parsers/text.ts, ts/yarn.lock
Closes open-flash/swf-parser#48
=> [all] Implement parser for `DefineCffFont`

CHANGELOG.md, rs/src/parsers/tags.rs, ts/src/lib/parsers/tags.ts
- Closes open-flash/swf-parser#39
- Closes open-flash/swf-parser#43
=> [all] Implement parser for `EnableDebugger`

CHANGELOG.md, rs/src/parsers/tags.rs, rs/src/parsers/text.rs, ts/src/lib/parsers/tags.ts, ts/src/lib/parsers/text.ts
Closes open-flash/swf-parser#42
=> [all] Implement parser for `DefineFontInfo2`

CHANGELOG.md, rs/src/parsers/tags.rs, ts/src/lib/parsers/tags.ts
Closes open-flash/swf-parser#49
=> [all] Implement parser for `Telemetry`

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, ts/package.json
- **[Breaking change]** Update to `swf-tree@0.9`.
- **[Feature]** Implement parser for `DefineButton` (thanks [@pheki](https://github.com/pheki)) ([#31](https://github.com/open-flash/swf-parser/issues/31)).
- **[Feature]** Implement parser for `DefineButtonSound` ([#34](https://github.com/open-flash/swf-parser/issues/34)).
- **[Feature]** Implement parser for `DefineText2` ([#37](https://github.com/open-flash/swf-parser/issues/37)).
- **[Feature]** Implement parser for `DefineButtonColorTransform` ([#35](https://github.com/open-flash/swf-parser/issues/35)).
- **[Feature]** Implement parser for `EnablePostscript` ([#92](https://github.com/open-flash/swf-parser/issues/92)).
- **[Feature]** Implement parser for `DefineVideoStream` ([#40](https://github.com/open-flash/swf-parser/issues/40)). …
=> [all] Release v0.9.0

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, rs/fuzz/Cargo.lock, ts/package.json
- **[Breaking change]** Refactor consumer API. The library now exports a function named
`parseSwf` (TS) or `parse_swf` (Rust) at its root ([#11](https://github.com/open-flash/swf-parser/issues/11)).
- **[Breaking change]** Update to `swf-types@0.10` (new `swf-tree`).
- **[Breaking change]** Make the parsers stateless by parsing font alignment zones based on available input instead of memorized glyph count.
- **[Feature]** Add invalid tag error recovery.
- **[Feature]** Add experimental streaming parser.
- **[Fix]** Remove `nom` macros.
- **[Fix]** Add `clippy` support.
- **[Fix]** **Fix panics found with fuzzing.**
- **[Fix]** Propagate string encoding errors.
- **[Fix]** Fix panic on invalid image type.
- **[Fix]** Fix panic on incomplete `DefineBitsLossless`.
- **[Fix]** Fix panic on …
=> [all] Release v0.10.0

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, rs/README.md, rs/fuzz/Cargo.lock, rs/src/complete/tag.rs, rs/src/lib.rs, rs/src/streaming/movie.rs, ts/.gitmodules, ts/gulpfile.ts, ts/package.json, ts/src/lib/parsers/tags.ts, ts/yarn.lock
Update all dependencies. Most importantly, update to `swf-types@0.11`.
=> [all] Update to `swf-types@0.11`

CHANGELOG.md, rs/Cargo.lock, rs/Cargo.toml, rs/fuzz/Cargo.lock, ts/package.json
- **[Breaking change]** Update to `swf-types@0.11`.
- **[Fix]** Update dependencies.
=> [all] Release v0.11.0

ts/README.md
This is just a suggestion to shorten the example. I felt like the abstraction isn't needed here unless the usage example will become more extensive.
=> simplified usage example

rs/Cargo.lock, rs/Cargo.toml
=> Upgrade and update dependencies.

.github/workflows/check-rs.yml, .github/workflows/check-ts.yml, CHANGELOG.md
Mention new GitHub Actions integration, add TypeScript section
=> [all] Update `CHANGELOG.md`
