open-flash/swf-parser

rs/Cargo.lock
rs/Cargo.toml
rs/src/parsers/sound.rs
rs/src/parsers/tags.rs
ts/package.json
ts/src/lib/parsers/sound.ts
ts/src/lib/parsers/tags.ts
ts/src/test/movie-from-bytes.spec.ts
ts/yarn.lock

Update to `swf-tree@0.3.0` (refactored sound tags) and implement sound stream parsers.

[all] Add support for sound streams

---

rs/Cargo.lock
rs/Cargo.toml
rs/README.md
rs/src/lib.rs
rs/src/parsers/sound.rs
rs/src/parsers/tags.rs
ts/package.json
ts/src/lib/parsers/sound.ts
ts/src/lib/parsers/tags.ts
ts/yarn.lock

Update to `swf-tree@0.4.x` and implement parsers for the following tags: `StartSound`, `ScriptLimits`, `SymbolClass`, `DoAbc`, `StartSound2`.

[all] Implement parsers to support `homestuck-02971`

---

rs/src/parsers/button.rs
ts/src/lib/parsers/button.ts
ts/src/lib/parsers/tags.ts
ts/src/test/movie-from-bytes.spec.ts

The parser failed to use action offsets to consume individual `ButtonCondAction`, instead it consumed the whole input and then tried to read the next `ButtonCondAction`.
Reported by @eddyb in https://github.com/open-flash/swf-parser/pull/5#issuecomment-479183906

[all] Fix support for DefineButton2 with multiple ButtonCondAction

---

ts/src/test/movie-from-bytes.spec.ts

Do not test against SWF files with uncertain licenses.

[all] Update test samples

---

rs/src/parsers/button.rs
ts/src/lib/parsers/button.ts

The parser was parsing the `ButtonCond` flags in the wrong order.
Reported and solved by @eddyb.
See: https://github.com/open-flash/swf-parser/pull/14#issuecomment-480501640

[Fix] Fix `ButtonCond` parser

---

rs/README.md
ts/README.md

The Rust and Typescript "Contributing" instruction were mixed. This commit fixes it. It also adds instructions to fuzz the Rust implementation.

[all] Fix contributing instructions

---

rs/src/parsers/tags.rs
ts/src/lib/parsers/tags.ts

This commit adds placeholder parsers for all the remaining tags defined by the SWF spec. This allows to better track the overall progress of the parser and provide better errors to consumers. According to the Rust implementation 45 out of 64 parsers are implemented.

[all] Add placeholders for missing implementations

---

ts/package.json
ts/src/lib/parsers/movie.ts
ts/yarn.lock

This commit fixes the dependency on Node's `zlib` in favor of `pako`. It should provide better better browser support. It also removes one of the last points where Node's `Buffer` was required (in favor of simply `Uint8Array`).

[ts] Replace `zlib` dependency with `pako`

---

rs/src/lib.rs
rs/src/parsers/movie.rs
rs/src/parsers/tags.rs

For consistency with the Typescript implementation and naming convention in the lib, this commit renames Rust's `parse_swf_tag` to `parse_tag`.

[rs] Rename `parse_swf_tag` to `parse_tag`

---

CHANGELOG.md
rs/Cargo.lock
rs/Cargo.toml
ts/package.json

- **[Breaking change]** Update to `swf-tree@0.6.0`.
- **[Internal]** Refactor tests.
- **[Internal]** Add `CHANGELOG.md`
- **[Fix]** Inflate zlib payloads with `pako` instead of Node's `zlib` (should improve browser support).
- **[Breaking change]** Rename `parse_swf_tag` to `parse_tag`.

[all] Release v0.5.0

---

CHANGELOG.md
rs/src/parsers/text.rs
ts/src/lib/parsers/morph-shape.ts
ts/src/lib/parsers/shape.ts
ts/src/lib/parsers/text.ts
ts/src/test/tags.spec.ts

This commit fixes the `TextRecord` parsers: the `has_offset_x` and `has_offset_y` flags were swapped. It caused the `DefineText` tag in the `hello-world` movie to be misparsed.

[all] Fix `TextRecord` flags parsing

---

CHANGELOG.md
rs/Cargo.lock
rs/Cargo.toml
ts/package.json

- **[Fix]** Ensure `align` is always defined in `DefineDynamicText`.
- **[Internal]** Update test samples.
- **[Fix]** Fix support for `PlaceObject1` with `ColorTransform`.

[all] Release v0.5.2

---

CHANGELOG.md
rs/src/parsers/tags.rs
ts/src/lib/parsers/tags.ts

I've implemented parsers (for both Rust and Typescript) for the DefineBinaryData tag, closing #46. I've done some testing locally, but if you have an SWF you'd like to use for testing this, I can implement a test for it as well.

Implement parsers for DefineBinaryData tag

---

.travis.yml
CHANGELOG.md
ts/gulpfile.ts
ts/package.json
ts/yarn.lock

This commit is a quick-fix for the build tools. It changes the default to use CommonJS for the tests until ESM is more stable.

[ts] Update build tools

---

CHANGELOG.md
rs/Cargo.lock
rs/Cargo.toml
ts/package.json

- **[Feature]** Implement parser for `DefineBinaryData` (thanks [@dmarcuse](https://github.com/dmarcuse)).
- **[Fix]** Parse PNG integers as big endians.
- **[Fix]** Stop at end of block or nul byte (whichever comes first) when parsing `DefineFont3`.
- **[Internal]** Update build tools.

[all] Release v0.5.3

---

CHANGELOG.md
README.md
rs/README.md
ts/README.md

This commit clarifies that the project commands must be run from the `rs` or `ts` directories, not the repo root.

[all] Update `Contributing` sections in `README.md`

---

.travis.yml
CHANGELOG.md
rs/rustfmt.toml
rs/src/lib.rs
rs/src/main.rs
rs/src/parsers/basic_data_types.rs
rs/src/parsers/button.rs
rs/src/parsers/display.rs
rs/src/parsers/gradient.rs
rs/src/parsers/header.rs
rs/src/parsers/image.rs
rs/src/parsers/morph_shape.rs
rs/src/parsers/movie.rs
rs/src/parsers/shape.rs
rs/src/parsers/sound.rs
rs/src/parsers/tags.rs
rs/src/parsers/text.rs
rs/src/state.rs

Hello!
I added rustfmt to the project, customizing the indentation to be 2 spaces. I believe you'd also prefer binop_separator = "Back" (see https://rust-lang.github.io/rustfmt/#binop_separator), but as its still unstable, I left it commented out....
Contributes to issue #25, I was going to also add clippy, but some lints are related to code generated inside nom macros! and as you'll probably have to update nom to 5.0 eventually (which is focused on function instead of macros) I decided to wait...
Also, I ran rustfmt in your name as you're the actual author of those lines...
To format your code just install rustfmt with:
```
rustup component add rustfmt
```
And to run its as simple as:
```
cargo fmt
```
Thanks for this amazing project 😉

[rs] Add rustfmt to project

---

ts/src/lib/parsers/tags.ts
ts/src/lib/parsers/text.ts

This commit adds the TS implementation for `DefineText2`, it is missing from open-flash/swf-parser#94.

[ts] Implement parser for `DefineText2`

---

CHANGELOG.md
rs/src/lib.rs
rs/src/parsers/basic_data_types.rs
rs/src/parsers/button.rs
rs/src/parsers/display.rs
rs/src/parsers/gradient.rs
rs/src/parsers/header.rs
rs/src/parsers/morph_shape.rs
rs/src/parsers/shape.rs
rs/src/parsers/sound.rs
rs/src/parsers/tags.rs
rs/src/parsers/text.rs

This commit completes the migration to `nom@5` by removing all its macros, in favor of functions.

[rs] Remove `nom` macros

---

CHANGELOG.md
rs/src/complete/tag.rs
rs/src/lib.rs
rs/src/stream_buffer.rs
rs/src/streaming/movie.rs
rs/src/streaming/parser.rs
rs/src/streaming/tag.rs

This commit adds an initial version of an SWF streaming parser. The test gives an example how to use it. This parser uses the _type state_ pattern to ensure the user first consumes the SWF header before parsing the tags.
There are some redundancies in the code and the error handling should be improved in further commits.
The streaming parser does not support LZMA yet. `lzma-rs` currently requires the inpput to be fully buffered.

[rs] Add initial streaming parser

---

CHANGELOG.md
rs/Cargo.lock
rs/Cargo.toml
rs/src/complete/movie.rs
rs/src/complete/tag.rs
rs/src/lib.rs
rs/src/streaming/tag.rs
ts/package.json
ts/src/lib/parsers/tags.ts
ts/src/test/tags.spec.ts
ts/yarn.lock

This commit updates the parser to support incomplete tag headers, tag bodies and invalid tag bodies. It uses the new `Raw` tag to represents these invalid states without aborting the whole movie parsing.

[all] Add invalid tag error recovery

---

CHANGELOG.md
ts/gulpfile.ts

This commit fixes the pre-release npm tag. Instead of being published with the `next` tag, pre-releases used the default `latest` tag.

[ts] Fix pre-release npm tag

---

rs/src/streaming/tag.rs
ts/src/lib/errors/incomplete-tag-header.ts
ts/src/lib/errors/incomplete-tag.ts
ts/src/lib/parsers/tags.ts
ts/src/test/tags.spec.ts

This commit updates the TS error recovery mechanism to align it with the Typescript implementation: unknown codes and invalid tag bodies now produce a `RawBody` tag.

[ts] Add support for invalid tag body

---

CHANGELOG.md
ts/src/lib/parsers/tags.ts
ts/src/test/tags.spec.ts

This commit ports the `DefineGlyphFont` offset check from Rust to Typescript.

[ts] Detect invalid `DefineGlyphFont` offsets

---

CHANGELOG.md
rs/README.md
rs/src/complete/movie.rs
rs/src/complete/tag.rs
rs/src/lib.rs
ts/README.md
ts/src/lib/index.ts
ts/src/lib/parsers/movie.ts
ts/src/test/movies.spec.ts

The library now exports a function named `parseSwf` (TS) or `parse_swf` (Rust) at its root. This commit also normalizes the naming convention around "SWF", "Payload" and "Movie" based on the model documented on the Open Flash website.
Closes open-flash/swf-parser#11

[all] Refactor consumer API

---

rs/src/streaming/decompress.rs
rs/src/streaming/movie.rs
rs/src/streaming/parser/deflate.rs
rs/src/streaming/parser/mod.rs

Return a runtime error instead of a panic when failing to decompress the movie payload due to a disable feature.

[rs] Avoid panic on missing feature

---

CHANGELOG.md
rs/Cargo.lock
rs/Cargo.toml
rs/bin/Cargo.toml
rs/fuzz/Cargo.lock
rs/fuzz/Cargo.toml
rs/src/streaming/decompress.rs
rs/src/streaming/movie.rs
rs/src/streaming/parser/deflate.rs
rs/src/streaming/parser/mod.rs

Update dependencies, update to Rust 2021, use explicit feature syntax (requires Rust 1.60.0).

[rs] Require Rust 1.60.0

---

CHANGELOG.md
rs/Cargo.lock
rs/Cargo.toml
rs/fuzz/Cargo.lock
ts/package.json

- **[Breaking change]** Require Rust `1.60.0`.
- **[Internal]** Migrate from Travis CI to GitHub Actions.
- **[Feature]** You may opt out from compression support. Compression is now
provided by the enabled-by-default features `deflate` and `lzma`.
- **[Feature]** Add support streaming support for movies using the `Deflate`
compression method.
- **[Fix]** Update dependencies ([#147](https://github.com/open-flash/swf-types/issues/147)).
- **[Breaking change]** Compile to `.mjs`.
- **[Fix]** Update dependencies.
- **[Internal]** Use Yarn's Plug'n'Play linker.

[all] Release v0.14.0
